### ISSUE TITLE
Task :smithy-typescript-codegen:compileJava fails with error "incompatible types"

### ISSUE THREAD

**Issue by trivikr** [awslabs/smithy-typescript#69]
Followed steps in https://github.com/awslabs/smithy-typescript#steps-to-build

```console
./gradlew build

> Task :smithy-typescript-codegen:compileJava
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java:219: error: incompatible types: Model cannot be converted to ShapeIndex
        return member.getMemberTrait(model, DocumentationTrait.class)
                                     ^
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java:88: error: cannot find symbol
                .shapes(ServiceShape.class)
                ^
  symbol:   method shapes(Class<ServiceShape>)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java:209: error: cannot find symbol
                .getShape(getService())
                ^
  symbol:   method getShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:210: error: incompatible types: invalid method reference
                            .forEach(serializingDocumentShapes::add);
                                     ^
    incompatible types: Object cannot be converted to Shape
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:209: error: cannot find symbol
                            .map(member -> context.getModel().expectShape(member.getTarget()))
                                                             ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:239: error: cannot find symbol
                Shape target = model.expectShape(binding.getMember().getTarget());
                                    ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:283: error: cannot find symbol
                    Shape target = model.expectShape(binding.getMember().getTarget());
                                        ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:314: error: cannot find symbol
                    Shape target = model.expectShape(binding.getMember().getTarget());
                                        ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:325: error: cannot find symbol
                    MapShape prefixMap = model.expectShape(binding.getMember().getTarget()).asMapShape().get();
                                              ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:326: error: cannot find symbol
                    Shape target = model.expectShape(prefixMap.getValue().getTarget());
                                        ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:365: error: cannot find symbol
                Shape target = context.getModel().expectShape(binding.getMember().getTarget());
                                                 ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:578: error: cannot find symbol
                    StructureShape target = model.expectShape(outputId).asStructureShape().get();
                                                 ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:587: error: cannot find symbol
                Shape target = model.expectShape(binding.getMember().getTarget());
                                    ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:626: error: cannot find symbol
                Shape target = model.expectShape(binding.getMember().getTarget());
                                    ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:647: error: cannot find symbol
                Shape target = model.expectShape(binding.getMember().getTarget());
                                    ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:664: error: cannot find symbol
                        MapShape prefixMap = model.expectShape(binding.getMember().getTarget()).asMapShape().get();
                                                  ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:665: error: cannot find symbol
                        Shape target = model.expectShape(prefixMap.getValue().getTarget());
                                            ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:702: error: cannot find symbol
            Shape target = context.getModel().expectShape(binding.getMember().getTarget());
                                             ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java:154: error: cannot find symbol
            StructureShape inputShape = context.getModel().expectShape(operation.getInput().get())
                                                          ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java:301: error: cannot find symbol
            StructureShape outputShape = context.getModel().expectShape(outputId).asStructureShape().get();
                                                           ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java:162: error: cannot find symbol
                    StructureShape error = context.getModel().expectShape(errorId).asStructureShape().get();
                                                             ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java:94: error: cannot find symbol
        model.shapes(OperationShape.class).forEach(operationShape -> {
             ^
  symbol:   method shapes(Class<OperationShape>)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java:300: error: cannot find symbol
        Shape targetShape = model.getShape(shape.getTarget())
                                 ^
  symbol:   method getShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java:73: error: cannot find symbol
        nonTraits = context.getModelWithoutTraitShapes();
                           ^
  symbol:   method getModelWithoutTraitShapes()
  location: variable context of type PluginContext
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java:141: error: no suitable constructor found for Walker(Model)
        Set<Shape> serviceShapes = new TreeSet<>(new Walker(nonTraits).walkShapes(service));
                                                 ^
    constructor Walker.Walker(ShapeIndex) is not applicable
      (argument mismatch; Model cannot be converted to ShapeIndex)
    constructor Walker.Walker(NeighborProvider) is not applicable
      (argument mismatch; Model cannot be converted to NeighborProvider)
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
25 errors

> Task :smithy-typescript-codegen:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smithy-typescript-codegen:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 15s
1 actionable task: 1 executed
```

**Comment by trivikr** [comment]
`./gradlew build --info`

```console
Initialized native services in: /Users/trivikr/.gradle/native
The client will now receive all logging from the daemon (pid: 30974). The daemon log file: /Users/trivikr/.gradle/daemon/5.6.2/daemon-30974.out.log
Starting 4th build in daemon [uptime: 35 mins 41.524 secs, performance: 99%, non-heap usage: 49% of 268.4 MB]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '/Users/trivikr/workspace/smithy-typescript/settings.gradle.kts'.
Projects loaded. Root project using build file '/Users/trivikr/workspace/smithy-typescript/build.gradle.kts'.
Included projects: [root project 'smithy-typescript', project ':smithy-typescript-codegen', project ':smithy-typescript-codegen-test']

> Configure project :
Evaluating root project 'smithy-typescript' using build file '/Users/trivikr/workspace/smithy-typescript/build.gradle.kts'.

> Configure project :smithy-typescript-codegen
Evaluating project ':smithy-typescript-codegen' using build file '/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/build.gradle.kts'.

> Configure project :smithy-typescript-codegen-test
Evaluating project ':smithy-typescript-codegen-test' using build file '/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen-test/build.gradle.kts'.
No Smithy model dependencies were found in the JAR, assuming Smithy CLI version 0.9.5
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':jar', task ':assemble', task ':checkstyleMain', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':checkstyleTest', task ':spotbugsMain', task ':spotbugsTest', task ':test', task ':check', task ':build', task ':smithy-typescript-codegen:compileJava', task ':smithy-typescript-codegen:processResources', task ':smithy-typescript-codegen:classes', task ':smithy-typescript-codegen:jar', task ':smithy-typescript-codegen:assemble', task ':smithy-typescript-codegen:checkstyleMain', task ':smithy-typescript-codegen:compileTestJava', task ':smithy-typescript-codegen:processTestResources', task ':smithy-typescript-codegen:testClasses', task ':smithy-typescript-codegen:checkstyleTest', task ':smithy-typescript-codegen:spotbugsMain', task ':smithy-typescript-codegen:spotbugsTest', task ':smithy-typescript-codegen:test', task ':smithy-typescript-codegen:jacocoTestReport', task ':smithy-typescript-codegen:check', task ':smithy-typescript-codegen:build', task ':smithy-typescript-codegen:javadoc', task ':smithy-typescript-codegen-test:compileJava', task ':smithy-typescript-codegen-test:processResources', task ':smithy-typescript-codegen-test:classes', task ':smithy-typescript-codegen-test:jar', task ':smithy-typescript-codegen-test:smithyBuildJar', task ':smithy-typescript-codegen-test:assemble', task ':smithy-typescript-codegen-test:compileTestJava', task ':smithy-typescript-codegen-test:processTestResources', task ':smithy-typescript-codegen-test:testClasses', task ':smithy-typescript-codegen-test:test', task ':smithy-typescript-codegen-test:check', task ':smithy-typescript-codegen-test:build']
:compileJava (Thread[Execution worker for ':',5,main]) started.

> Task :compileJava NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/main/java', not found
Skipping task ':compileJava' as it has no source files and no previous output files.
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.006 secs.
:processResources (Thread[Execution worker for ':',5,main]) started.

> Task :processResources NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/main/resources', not found
Skipping task ':processResources' as it has no source files and no previous output files.
:processResources (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:classes (Thread[Execution worker for ':',5,main]) started.

> Task :classes UP-TO-DATE
Skipping task ':classes' as it has no actions.
:classes (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:jar (Thread[Daemon worker Thread 4,5,main]) started.

> Task :jar SKIPPED
Skipping task ':jar' as task onlyIf is false.
:jar (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.0 secs.
:assemble (Thread[Daemon worker Thread 4,5,main]) started.

> Task :assemble UP-TO-DATE
Skipping task ':assemble' as it has no actions.
:assemble (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.0 secs.
:checkstyleMain (Thread[Daemon worker Thread 4,5,main]) started.

> Task :checkstyleMain NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/main/java', not found
Skipping task ':checkstyleMain' as it has no source files and no previous output files.
:checkstyleMain (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.003 secs.
:compileTestJava (Thread[Daemon worker Thread 4,5,main]) started.

> Task :compileTestJava NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/test/java', not found
Skipping task ':compileTestJava' as it has no source files and no previous output files.
:compileTestJava (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.007 secs.
:processTestResources (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :processTestResources NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/test/resources', not found
Skipping task ':processTestResources' as it has no source files and no previous output files.
:processTestResources (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.001 secs.
:testClasses (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :testClasses UP-TO-DATE
Skipping task ':testClasses' as it has no actions.
:testClasses (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.0 secs.
:checkstyleTest (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :checkstyleTest NO-SOURCE
file or directory '/Users/trivikr/workspace/smithy-typescript/src/test/java', not found
Skipping task ':checkstyleTest' as it has no source files and no previous output files.
:checkstyleTest (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.001 secs.
:spotbugsMain (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :spotbugsMain NO-SOURCE
Skipping task ':spotbugsMain' as it has no source files and no previous output files.
:spotbugsMain (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.001 secs.
:spotbugsTest (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :spotbugsTest NO-SOURCE
Skipping task ':spotbugsTest' as it has no source files and no previous output files.
:spotbugsTest (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.005 secs.
:test (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :test NO-SOURCE
Skipping task ':test' as it has no source files and no previous output files.
:test (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.002 secs.
:check (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :check UP-TO-DATE
Skipping task ':check' as it has no actions.
:check (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.0 secs.
:build (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :build UP-TO-DATE
Skipping task ':build' as it has no actions.
:build (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.0 secs.
:smithy-typescript-codegen:compileJava (Thread[Execution worker for ':' Thread 3,5,main]) started.

> Task :smithy-typescript-codegen:compileJava FAILED
Caching disabled for task ':smithy-typescript-codegen:compileJava' because:
  Build cache is disabled
Task ':smithy-typescript-codegen:compileJava' is not up-to-date because:
  Task has failed previously.
All input files are considered out-of-date for incremental task ':smithy-typescript-codegen:compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java:219: error: incompatible types: Model cannot be converted to ShapeIndex
        return member.getMemberTrait(model, DocumentationTrait.class)
                                     ^
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java:88: error: cannot find symbol
                .shapes(ServiceShape.class)
                ^
  symbol:   method shapes(Class<ServiceShape>)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java:209: error: cannot find symbol
                .getShape(getService())
                ^
  symbol:   method getShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:210: error: incompatible types: invalid method reference
                            .forEach(serializingDocumentShapes::add);
                                     ^
    incompatible types: Object cannot be converted to Shape
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:209: error: cannot find symbol
                            .map(member -> context.getModel().expectShape(member.getTarget()))
                                                             ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:239: error: cannot find symbol
                Shape target = model.expectShape(binding.getMember().getTarget());
                                    ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:283: error: cannot find symbol
                    Shape target = model.expectShape(binding.getMember().getTarget());
                                        ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:314: error: cannot find symbol
                    Shape target = model.expectShape(binding.getMember().getTarget());
                                        ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:325: error: cannot find symbol
                    MapShape prefixMap = model.expectShape(binding.getMember().getTarget()).asMapShape().get();
                                              ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:326: error: cannot find symbol
                    Shape target = model.expectShape(prefixMap.getValue().getTarget());
                                        ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:365: error: cannot find symbol
                Shape target = context.getModel().expectShape(binding.getMember().getTarget());
                                                 ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:578: error: cannot find symbol
                    StructureShape target = model.expectShape(outputId).asStructureShape().get();
                                                 ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:587: error: cannot find symbol
                Shape target = model.expectShape(binding.getMember().getTarget());
                                    ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:626: error: cannot find symbol
                Shape target = model.expectShape(binding.getMember().getTarget());
                                    ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:647: error: cannot find symbol
                Shape target = model.expectShape(binding.getMember().getTarget());
                                    ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:664: error: cannot find symbol
                        MapShape prefixMap = model.expectShape(binding.getMember().getTarget()).asMapShape().get();
                                                  ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:665: error: cannot find symbol
                        Shape target = model.expectShape(prefixMap.getValue().getTarget());
                                            ^
  symbol:   method expectShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java:702: error: cannot find symbol
            Shape target = context.getModel().expectShape(binding.getMember().getTarget());
                                             ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java:154: error: cannot find symbol
            StructureShape inputShape = context.getModel().expectShape(operation.getInput().get())
                                                          ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java:301: error: cannot find symbol
            StructureShape outputShape = context.getModel().expectShape(outputId).asStructureShape().get();
                                                           ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java:162: error: cannot find symbol
                    StructureShape error = context.getModel().expectShape(errorId).asStructureShape().get();
                                                             ^
  symbol:   method expectShape(ShapeId)
  location: class Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java:94: error: cannot find symbol
        model.shapes(OperationShape.class).forEach(operationShape -> {
             ^
  symbol:   method shapes(Class<OperationShape>)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java:300: error: cannot find symbol
        Shape targetShape = model.getShape(shape.getTarget())
                                 ^
  symbol:   method getShape(ShapeId)
  location: variable model of type Model
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java:73: error: cannot find symbol
        nonTraits = context.getModelWithoutTraitShapes();
                           ^
  symbol:   method getModelWithoutTraitShapes()
  location: variable context of type PluginContext
/Users/trivikr/workspace/smithy-typescript/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java:141: error: no suitable constructor found for Walker(Model)
        Set<Shape> serviceShapes = new TreeSet<>(new Walker(nonTraits).walkShapes(service));
                                                 ^
    constructor Walker.Walker(ShapeIndex) is not applicable
      (argument mismatch; Model cannot be converted to ShapeIndex)
    constructor Walker.Walker(NeighborProvider) is not applicable
      (argument mismatch; Model cannot be converted to NeighborProvider)
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
25 errors
:smithy-typescript-codegen:compileJava (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.775 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smithy-typescript-codegen:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
1 actionable task: 1 executed
```

**Comment by mtdowling** [comment]
Looks like this was due to using features that weren't yet published to maven central. This is how we've been iterating as fast as possible -- basically using maven local before periodically publishing to maven central.
